language: ruby
cache: bundler
rvm:
  - 2.1.1
before_script:
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/transitmix_test
deploy:
  provider: heroku
  api_key:
    secure: hWV9+hAsC50G2yMXYz9h3M1fYALnNVc/SrUxiemcZ0B9fWKGCQ8qJCrU57OwtU6lnxTaVZXVvOrHoKjLYCd3NwEqFary6DuHoLPYXT6tZp58B9TX9EHF0O++0mVa3SyO5rDyO6XSz7BDXj1rLT2u+vRzC2I7tM9uVmMkZKwIeb4=
  app: transitmix-staging
  run:
    - "rake db:migrate"
    - restart
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/b4187edb-11eb-429e-bc0a-9eb92f6eead6/status
